import './globals.css';
import { Providers } from './providers';
import Navbar from './components/Navbar';
import { Inter } from 'next/font/google';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';


const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: "MyShop-USER",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          {/* <LoginPage/> */}
          <ToastContainer/>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
